package uk.ac.aber.dcs.CS31620.quizapp.datasource

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * This is a dataclass that is the Question entity for the room database.
 * @Entity is use here o make it a Room entity.
 * This defines the schema of 'Question' table in the database.
 *
 * The 'ID' is automatically generated by ROOM.
 * The 'questionText' holds the text for the questions.
 *
 * @param id : unique identifier generated by ROOM
 * @param questionText: the text of the question
 */
@Entity()
data class Question(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val questionText : String,
)
